name: Issue Report
description: Use this form to report an issue.
title: "[MOD_ID]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please remember, bugs are unintentional and your understanding is appreciated. Maintain a respectful tone throughout.
        ⚠ **Important:** You don't have to change the [MOD_ID] yourself — this is done by a GitHub Action.

  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal Instance Test
      description: "Check if the issue persists with only this mod and its dependencies active."
      options:
        - label: "Yes, I've tested on a minimal instance."
          required: true

  - type: checkboxes
    id: has_checked_for_similar_issues
    attributes:
      label: Check for Similar Issues
      description: "Please search the issues to check if this bug has already been reported."
      options:
        - label: "Yes, I have checked for similar issues."
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - "Fabric"
        - "NeoForge"
    validations:
      required: true

  - type: input
    id: loader_version
    attributes:
      label: Loader Version
      placeholder: "e.g., Fabric Loader 0.17.2 or NeoForge 21.1.205"
    validations:
      required: true

  - type: dropdown
    id: minecraft_version
    attributes:
      label: Minecraft Version
      options:
        - "1.21.1"
    validations:
      required: true

  - type: dropdown
    id: mod
    attributes:
      label: Mod
      options:
        - "Vinery"
        - "Meadow"
        - "Bakery"
        - "Candlelight"
        - "HerbalBrews"
        - "BloomingNature"
        - "Farm & Charm"
        - "Brewery"
        - "Beachparty"
        - "Camping"
        - "Harvestfall"
        - "AppleWood"
        - "SafariBanquet"
        - "Seasonal Gifts"
        - "WilderNature"
        - "Lili's Lucky Lures"
        - "Furniture"
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: "e.g., 1.3.14"
    validations:
      required: true

  - type: input
    id: java_version
    attributes:
      label: Java Version
      placeholder: "e.g., Java 21.0.7 (or 17.0.9)"
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating System
      placeholder: "e.g., Windows 11 build 26100 / macOS 14.6"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Provide a comprehensive description of the issue."
      placeholder: "What happened? Any errors on screen? Crash vs. logic bug?"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: "Enumerate the steps needed to replicate the issue."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: other_mods
    attributes:
      label: Other Mods Present
      description: "List other mods (and versions) present when reproducing the issue. Empty if minimal instance."
      placeholder: "e.g., Sodium 0.6.13, EntityCulling 1.8.2"
    validations:
      required: false

  - type: input
    id: logs
    attributes:
      label: Link to logs
      description: "Upload logs via https://pastebin.com/ or https://mclo.gs and provide the link here."
      placeholder: "https://mclo.gs/abcdef"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Crash Reports
      description: "Optional. Drag & drop images here, or paste additional crash report snippets."
    validations:
      required: false
