name: Issue Report
description: Report a bug or unexpected behavior.
title: "[MOD_ID]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue.

        ⚠ Notes:
        - Minecraft **1.21.1 requires Java 21**
        - Unsupported versions will be closed

  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal Instance Test
      description: Does the issue still happen with only this mod and its dependencies?
      options:
        - label: Yes, I've tested on a minimal instance.
          required: true

  - type: checkboxes
    id: has_checked_for_similar_issues
    attributes:
      label: Similar Issues
      description: Please check if this issue was already reported.
      options:
        - label: Yes, I have checked for similar issues.
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Fabric
        - NeoForge
    validations:
      required: true

  - type: dropdown
    id: minecraft_version
    attributes:
      label: Minecraft Version
      options:
        - "1.21.1"
    validations:
      required: true

  - type: dropdown
    id: mod
    attributes:
      label: Mod
      options:
        - Vinery
        - Meadow
        - Bakery
        - Candlelight
        - HerbalBrews
        - BloomingNature
        - Farm & Charm
        - Brewery
        - Beachparty
        - Camping
        - Harvestfall
        - AlpineWhispers
        - WilderNature
        - Lili's Lucky Lures
        - Furniture
        - Pottery
        - Hearth & Timber
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: e.g. 1.5.3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      placeholder: What happened? What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Logs
      description: Upload logs via https://mclo.gs and paste the link.
      placeholder: https://mclo.gs/abcdef
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Drag & drop images or paste crash snippets here.
