name: Issue Report
description: Use this form to report an issue.
title: "[MOD_ID]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please remember, bugs are unintentional and your understanding is appreciated. Maintain a respectful tone throughout.
        ⚠ **Important:** You don't have to change the [MOD_ID] by yourself - this is done by a Github Action.

  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal Instance Test
      description: "Check if the issue persists with only this mod and its dependencies active."
      options:
        - label: "Yes, I've tested on a minimal instance."
      
  - type: checkboxes
    id: has_checked_for_similar_issues
    attributes:
      label: Check for Similar Issues
      description: 'Please [search 🔍 the issues](https://github.com/Let-s-Do-Collection/Let-s-Do-Hub/issues) to check if this bug has already been reported.'
      options:
        - label: "Yes, I have checked for similar issues."

  - type: markdown
    attributes:
      value: |
        Detail your issue below.  
        **Please Note:** This report form is intended for reporting issues and is not for general questions or assistance with uncertainties. For that, the wikis and Discord are available.

  - type: markdown
    attributes:
      value: |
        ⚠ **Important:** The mod *Camping* is **not** managed here.  
        → Please report issues related to *Camping* here: [Camping Issues](https://github.com/satisfyu/Camping/issues)

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "e.g., 1.20.1"
    validations:
      required: true

  - type: dropdown
    id: mod
    attributes:
      label: Mod
      options:
        - "Vinery"
        - "Meadow"
        - "Bakery"
        - "Candlelight"
        - "HerbalBrews"
        - "BloomingNature"
        - "Farm&Charm"
        - "Brewery"
        - "Beachparty"
        - "Camping (⚠ Report issues here: https://github.com/satisfyu/Camping/issues)"
        - "Harvestfall"
        - "AppleWood"
        - "SafariBanquet"
        - "Seasonal Gifts"
        - "WilderNature"
        - "Lilis Lucky Lures"
        - "Furniture"
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      placeholder: "e.g., 1.3.14"
    validations:
      required: true

  - type: checkboxes
    id: using_the_latest_version
    attributes:
      label: Latest Version
      description: "Are you using the latest version of the respective mod for the corresponding Minecraft version? Please note that older versions are no longer actively supported."
      options:
        - label: "Yes. I'm using the latest Version."

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Provide a comprehensive description of the issue."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: "Enumerate the steps needed to replicate the issue."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Upload logs via https://pastebin.com/ and provide the link here."
    validations:
      required: true
