name: Issue Report
description: Submit an issue report using this form.
body:
  - type: markdown
    attributes:
      value: "I understand that encountering bugs can be frustrating, but please remember that they are not introduced intentionally. I strive to make the mods as error-free as possible. Please avoid insults, passive aggressiveness, or any negative behavior while filling out this form."
  - type: markdown
    attributes:
      value: "Please describe your issue in detail."
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      placeholder: "e.g., 1.20.1"
    validations:
      required: true
  - type: input
    id: mod
    attributes:
      label: Mod Name and Version
      placeholder: "e.g., Vinery, 2.0.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Provide a detailed description of the issue."
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: "List the steps needed to reproduce the issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please upload logs from your launcher using sites like https://pastebin.com/"
  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal Instance Test
      description: "Have you tested the issue with only the mod in question and related mods?"
      options:
        - label: "Yes, I've tested this on a minimal instance."
  - type: checkboxes
    id: has_checked_for_similar_issues
    attributes:
      label: Check for Similar Issues
      description: "To help reduce our workload, please check if there is already a report for your issue."
      options:
        - label: "Yes, I have checked for similar issues."
  - type: markdown
    attributes:
      value: "Thank you for submitting your issue report! Please be patient while we work on a resolution."
