name: Auto Comment on New Issue

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  comment-if-fixed:
    if: "${{ github.event.label.name == 'fixed' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Post automatic reply
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: [
                "This issue has been marked as fixed and will be rolled out with the next release of the respective mod.",
                "",
                "Thanks so much for taking the time to report a bug!",
                "",
                "We'll take a look as soon as we get the chance and let you know here if we have any questions or need any more info.",
                "If you've got any extra info, screenshots or logs, feel free to add them any time!"
              ].join("\n")
            });
