name: Comment on "Fixed" Label

on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  comment-if-fixed:
    if: "${{ github.event.label.name == 'fixed' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Post fixed comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: [
                "This issue has been marked as fixed and will be rolled out with the next release of the respective mod.",
                "",
                "Thank you for your report and for being an active part of the [Let's Do] Series! ❤️"
              ].join("\n")
            });
